store/store_app/urls.py
from django.urls import path
from . import views

app_name = 'store'
urlpatterns = [
    path('books/', views.BookListView.as_view(), name='book_list'),
    path('book_detail/<int:pk>/', views.BookDetailView.as_view(), name='book_detail'),
    path('add-to-cart/<int:pk>/', views.add_to_cart, name='add_to_cart'),
    path('cart/', views.get_cart, name='cart'),
    path('checkout/', views.checkout, name='checkout'),

    # path('cart/', views.CartDetailView.as_view(), name='cart'),
]

store/store_sys/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', RedirectView.as_view(url='/store/books/')),
    path('store/', include('store_app.urls')),
    path('user/', include('store_users.urls')),
]

store/templates/store/book_detail.html
{% extends "base.html" %}
{% block content %}
    <h2>Post detail</h2>
    {{ object.instance.pk }}
    <div class="table-responsive">
        <table class="table align-middle">
            <tr>
                <td>Book</td>
                <td>{{ book.title }}</td>
            </tr>
            <tr>
                <td>Price</td>
                <td>{{ book.price }}</td>
            </tr>
            <tr>
                <td>Add to cart</td>
                <td><a href='{% url "store:add_to_cart" pk=book.id %}'>Add to Cart</a></td>
            </tr>
        </table>
    </div>
{% endblock %}

store/templates/store/book_list.html
{% extends "base.html" %}
{% block content %}
    <h2>Books list</h2>

    <table class="table table-hover">
        <thead class="table-dark">
        <tr>
            <td>Title</td>
            <td>Prise</td>
        </tr>
        </thead>
        <tbody>
        {% for a in book_list %}
        <tr>
            <td><a href='{% url "store:book_detail" pk=a.id %}'>{{ a.title }}</a></td>
            <td>{{ a.price }}</td>
        </tr>
        {% endfor %}
        </tbody>
    </table>


{% endblock %}

store/templates/store/cart_detail.html
{% extends "base.html" %}
{% block content %}
    <h2>Cart detail</h2>
    {{ object.instance.pk }}
    <div class="table-responsive">
        <table class="table table-hover">
            <thead class="table-dark">
            <tr>
                <td>Book</td>
                <td>Price</td>
                <td>Quantity</td>
                <td>Total</td>
            </tr>
            </thead>
            <tbody>
            {% for a in items_with_total_prices %}
            <tr>
                <td>{{ a.item.book_id.title }}</td>
                <td>{{ a.item.book_id.price }}</td>
                <td>{{ a.item.quantity }}</td>
                <td>{{ a.price }}</td>
            </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>
{% endblock %}

store/templates/store/cart_empty.html
{% extends "base.html" %}
{% block content %}
    <h2>Your cart is empty now<br>Try to add some books</h2>
{% endblock %}

store/templates/store/checkout.html
{% extends "base.html" %}
{% block content %}
    <h2>Checkout</h2>
    {{ object.instance.pk }}
    <div class="table-responsive">
        <table class="table table-hover">
            <thead class="table-dark">
            <tr>
                <td>Book</td>
                <td>Price</td>
                <td>Quantity</td>
                <td>Total</td>
            </tr>
            </thead>
            <tbody>
            {% for a in items_with_total_prices %}
            <tr>
                <td>{{ a.item.book_id.title }}</td>
                <td>{{ a.item.book_id.price }}</td>
                <td>{{ a.item.quantity }}</td>
                <td>{{ a.price }}</td>
            </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>
    <div>
        Total value of your order: {{ total_price }}
    </div>
    <form action= "{% url 'store:checkout' %}" method="POST" class="post-form">
        {% csrf_token %}
        <table class="table align-middle">
            {{ form.as_table }}
        </table>
        <button type="submit" class="save btn btn-secondary">Save</button>
    </form>
{% endblock %}