store/store_app/urls.py
from django.urls import path
from . import views

app_name = 'store'
urlpatterns = [
    path('books/', views.BookListView.as_view(), name='book_list'),
    path('book_detail/<int:pk>/', views.BookDetailView.as_view(), name='book_detail'),
    path('add-to-cart/<int:pk>/', views.add_to_cart, name='add_to_cart'),
    path('cart/', views.get_cart, name='cart'),
    path('checkout/', views.checkout, name='checkout'),

    # path('cart/', views.CartDetailView.as_view(), name='cart'),
]

store/store_sys/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', RedirectView.as_view(url='/store/books/')),
    path('store/', include('store_app.urls')),
    path('user/', include('store_users.urls')),
]

store/store_users/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views
# from rest_framework.routers import DefaultRouter
# from rest_framework.authtoken import views as token_view


app_name = 'store_users'
urlpatterns = [
    path('registration/', views.RegistrationView.as_view(), name='registration'),

    path("login/", auth_views.LoginView.as_view(), name="login"),
    path("logout/", auth_views.LogoutView.as_view(), name="logout"),
    path("user-detail/", views.UserDetailView.as_view(), name="user_detail"),
    path("user-update/", views.UserUpdateView.as_view(), name="user_update"),
    # path('api-token-auth/', token_view.obtain_auth_token)

]

store/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>

  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>{% block title %}Local Library{% endblock %}</title>
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css"
    integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"
      integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV"
      crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.bundle.min.js"
      integrity="sha384-LtrjvnR4Twt/qOuYxE721u19sVFLVSA4hf/rRt6PrZTmiPltdZcI7q7PXQBYTKyf"
      crossorigin="anonymous"></script>


  {% block extra_css %}
  {% endblock %}
  {% block extra_js %}
  {% endblock %}
</head>
<body>
<div class="container" style="padding-top: 60px;">
{% if messages %}
<div class="row">
  <div class="col-sm-12">
    {% for message in messages %}
      <div class="alert alert-success" role="alert">
        {{ message }}
      </div>
    {% endfor %}
  </div>
</div>
{% endif %}
</div>

<nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
  <div class="container-fluid">
    {% if request.user.is_authenticated %}
    <a class="navbar-brand" href="{% url 'store_users:user_detail' %}">{{ request.user.get_username }}</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    {% else %}
    <a class="navbar-brand" href="{% url 'store_users:login' %}?next={{ request.path }}">Login</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <a class="navbar-brand" href="{% url 'store_users:registration' %}?next={{ request.path }}">Registration</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
    </button>
    {% endif %}
    <div class="collapse navbar-collapse" id="navbarNavDropdown">
      <div class="navbar-nav">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{% url 'store:book_list' %}">Books</a>
        </li>
        {% if request.user.is_authenticated %}
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{% url 'store:cart' %}">Cart</a>
        </li>
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{% url 'store:checkout' %}">Checkout</a>
        </li>
        <div class="nav-item dropdown">
          <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            User functions
          </button>
          <ul class="dropdown-menu">
            <li><a class="dropdown-item" href="{% url 'store_users:user_detail' %}">My profile</a></li>
            <li><a class="dropdown-item" href="{% url 'store_users:logout' %}?next={% url 'store:book_list' %}">Logout</a></li>
        {% endif %}
          </ul>
        </div>
      </div>
    </div>
  </div>
</nav>
<div class="container">

{% block content %}{% endblock %}

</body>
</html>